### ISSUE TITLE
Error: EAGAIN, resource temporarily unavailable

### ISSUE THREAD

**Issue by shellscape** [mbostock/rw#3]
Running on Mac OSX Mavericks, Node 0.10.4. 

`rw.readSync('/dev/stdin', 'utf8');`

Error: EAGAIN, resource temporarily unavailable
  at Object.fs.readSync (fs.js:476:19)

**Comment by mbostock** [comment]
In Node 5.5, using console.warn breaks rw.writeFileSync to /dev/stdout, even though console.warn should only write to process.stderr.

Replacing `console.warn("foo")` with `process.stderr.write("foo\n")` seems to fix the problem. I don’t think there’s a way to fix that in this library, though.

**Comment by mschwartz** [comment]
EAGAIN is not handled in write-file-sync.js, so this bug will appear under various situations.

I see it in WebStorm while running the app under the debugger while trying to write to /dev/stdout.

**Comment by mbostock** [comment]
@mschwartz I’d love to be wrong here, but I don’t think it’s possible for rw.writeFileSync to handle EAGAIN because rw.writeFileSync is synchronous: there’s no way to wait for process.stderr or process.stdout to be ready again.

**Comment by mschwartz** [comment]
You are looping to write the data in chunks. You test for EPIPE and break.
No harm in adding the test for EAGAIN, IMO
