### ISSUE TITLE
Is it possible to write as a stream or using `appendFile`?

### ISSUE THREAD

**Issue by mrcoles** [mbostock/rw#9]
It appears that the only way to write to a file with this module is by writing the entire file at once. Would it be possible to expose writing a stream or something like `appendFile` for functions that need to process a lot of data and don’t want to hold it all in memory at once?

I’m looking to write a CLI script to request data from numerous db calls and dump it into logs. If it ends up being a lot of data, the script should be able to write to the file and free up memory for new data to write. Also, given it’s a CLI script, it makes sense for it to support writing to stdout and actual files.

**Comment by mbostock** [comment]
Hi @mrcoles. I’m not currently providing support for this library. I’d suggest using the Node `fs` APIs directly.

**Comment by mrcoles** [comment]
Oh, thanks. The abstraction you created with this package is quite nice. Do you know any good, succinct references for doing this with the `fs` methods?

**Comment by mbostock** [comment]
I think you can do this using rw by passing the `{flags: "a"}` as options (which goes through to fs.createWriteStream), but as I said, I don’t provide support. Sorry and good luck!
